#!/usr/bin/env node

/**
 * Regenerates the non-Ferrari constructor-win archive from Jolpica F1.
 *
 * Jolpica is the open-source, drop-in successor to the retired Ergast API:
 * https://github.com/jolpica/jolpica-f1
 * Endpoint: https://api.jolpi.ca/ergast/f1/results/1.json
 *
 * The API models some historic constructor/engine combinations separately.
 * f1TeamConfig.json deliberately groups retained aliases under the familiar
 * team identity (for example McLaren-Ford under McLaren and the works Team
 * Lotus combinations under Team Lotus). The config is also the explicit scope
 * boundary for the user-visible archive.
 *
 * Indianapolis-only chassis winners (Kurtis Kraft, Watson and Epperly) are not
 * included: their wins were Indianapolis 500 entries while that event counted
 * toward the World Drivers' Championship, rather than Formula One team wins.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(scriptDir, '..');
const configPath = path.join(rootDir, 'src/data/f1TeamConfig.json');
const outputPath = path.join(rootDir, 'src/data/f1Wins.generated.ts');
const endpoint = 'https://api.jolpi.ca/ergast/f1/results/1.json';
const pageSize = 100;

const teams = JSON.parse(await readFile(configPath, 'utf8'));
const sourceIdToTeam = new Map(
  teams.flatMap((team) => team.constructorIds.map((sourceId) => [sourceId, team])),
);

async function getPage(offset) {
  const response = await fetch(`${endpoint}?limit=${pageSize}&offset=${offset}`, {
    headers: { 'user-agent': 'classicverse-f1-archive/1.0' },
  });
  if (!response.ok) throw new Error(`Jolpica request failed (${response.status}) at offset ${offset}`);
  return response.json();
}

const firstPage = await getPage(0);
const totalResults = Number(firstPage.MRData.total);
const pages = [firstPage];
for (let offset = pageSize; offset < totalResults; offset += pageSize) {
  pages.push(await getPage(offset));
}

const races = pages.flatMap((page) => page.MRData.RaceTable.Races);
const winsByTeam = Object.fromEntries(
  teams.filter((team) => team.id !== 'ferrari').map((team) => [team.id, []]),
);

for (const race of races) {
  // Three early races have a shared drive, so the API returns multiple P1
  // result rows. A constructor still earned one race win; preserve all driver
  // and car numbers in the single archive record instead of double-counting it.
  const winnersByTeam = new Map();
  for (const result of race.Results) {
    const team = sourceIdToTeam.get(result.Constructor.constructorId);
    if (!team) continue;
    const existing = winnersByTeam.get(team.id) ?? [];
    existing.push(result);
    winnersByTeam.set(team.id, existing);
  }

  for (const [teamId, results] of winnersByTeam) {
    const first = results[0];
    winsByTeam[teamId].push({
      number: 0,
      year: Number(race.season),
      grand_prix: race.raceName.replace(/ Grand Prix$/, ''),
      circuit: race.Circuit.circuitName,
      car_number: [...new Set(results.map((result) => result.number))].join(' / '),
      driver: results
        .map((result) => `${result.Driver.givenName} ${result.Driver.familyName}`)
        .join(' / '),
      date: race.date,
      source_url: race.url,
      source_constructor: first.Constructor.name,
    });
  }
}

for (const wins of Object.values(winsByTeam)) {
  wins.sort((a, b) => a.date.localeCompare(b.date));
  wins.forEach((win, index) => { win.number = index + 1; });
}

const latestRace = races.at(-1);
const serializable = Object.fromEntries(
  Object.entries(winsByTeam).filter(([, wins]) => wins.length > 0),
);
const file = `// Generated by scripts/generate-f1-wins.mjs — do not edit by hand.\n` +
  `// Source: ${endpoint}\n` +
  `// Cutoff: ${latestRace.date} (${latestRace.raceName}).\n` +
  `// See the generator for constructor-alias and Indianapolis exclusions.\n\n` +
  `import type { ConstructorWin } from '@/types/f1';\n\n` +
  `export const F1_DATA_CUTOFF = ${JSON.stringify(latestRace.date)};\n` +
  `export const F1_DATA_CUTOFF_RACE = ${JSON.stringify(latestRace.raceName)};\n` +
  `export const F1_DATA_SOURCE = ${JSON.stringify(endpoint)};\n\n` +
  `export const F1_WINS_BY_TEAM: Record<string, ConstructorWin[]> = ${JSON.stringify(serializable, null, 2)};\n`;

await writeFile(outputPath, file, 'utf8');

const summary = teams.map((team) => {
  const count = team.id === 'ferrari' ? 'hand-authored' : (winsByTeam[team.id]?.length ?? 0);
  return `${team.name}: ${count}`;
});
console.log(`Wrote ${outputPath}`);
console.log(`Cutoff: ${latestRace.date} — ${latestRace.raceName}`);
console.log(summary.join('\n'));
