#!/usr/bin/env bash
set -euo pipefail

# Reuse the exact click generated by the app's physical tuning wheel, then place
# it at every visible wheel detent. MediaRecorder omits some isolated packets,
# so rebuilding those timestamps is more reliable than decoding its gaps.
ffmpeg -hide_banner -loglevel error -y \
  -i demo_videos/classicverse-radio-proper-audio-a-1.webm \
  -t 0.06 -af "asetpts=N/SR/TB" \
  demo_videos/classicverse-radio-knob-tick.wav

# Take A starts 0.274s before the audio capture. The power sound, boot sound,
# menu-open sound, station stream, and each knob click are aligned to the
# matching frame in the trimmed 41.5-second picture.
ffmpeg -hide_banner -loglevel error -y \
  -f lavfi -i "anullsrc=r=48000:cl=stereo:d=41.5" \
  -i demo_videos/classicverse-radio-proper-audio-a-0.webm \
  -i demo_videos/classicverse-radio-proper-audio-a-2.webm \
  -i demo_videos/classicverse-radio-knob-tick.wav \
  -filter_complex "
    [1:a]aresample=async=1:first_pts=0,adelay=1200|1200[system];
    [2:a]aresample=async=1:first_pts=0,adelay=5860|5860[station];
    [3:a]asplit=5[t0][t1][t2][t3][t4];
    [t0]adelay=4900|4900,volume=4[k0];
    [t1]adelay=27600|27600,volume=4[k1];
    [t2]adelay=31000|31000,volume=4[k2];
    [t3]adelay=34500|34500,volume=4[k3];
    [t4]adelay=38000|38000,volume=4[k4];
    [0:a][system][station][k0][k1][k2][k3][k4]amix=inputs=8:duration=first:normalize=0,alimiter=limit=0.92[out]
  " \
  -map "[out]" -c:a libmp3lame -b:a 192k \
  demo_videos/classicverse-radio-proper-a.mp3

# Take B begins on the same tuned frequency and continues for 18.5 seconds.
# Its live station graph starts with the cut, while the same native wheel click
# is placed at all six visible frequency changes.
ffmpeg -hide_banner -loglevel error -y \
  -f lavfi -i "anullsrc=r=48000:cl=stereo:d=18.5" \
  -i demo_videos/classicverse-radio-proper-audio-b-1.webm \
  -i demo_videos/classicverse-radio-knob-tick.wav \
  -filter_complex "
    [1:a]aresample=async=1:first_pts=0,adelay=63|63[station];
    [2:a]asplit=6[t0][t1][t2][t3][t4][t5];
    [t0]adelay=700|700,volume=4[k0];
    [t1]adelay=3600|3600,volume=4[k1];
    [t2]adelay=6600|6600,volume=4[k2];
    [t3]adelay=9600|9600,volume=4[k3];
    [t4]adelay=12600|12600,volume=4[k4];
    [t5]adelay=15500|15500,volume=4[k5];
    [0:a][station][k0][k1][k2][k3][k4][k5]amix=inputs=8:duration=first:normalize=0,alimiter=limit=0.92[out]
  " \
  -map "[out]" -c:a libmp3lame -b:a 192k \
  demo_videos/classicverse-radio-proper-b.mp3
