'use client';

import { isFolder, type AppProps, type OSNode } from '../types';
import { childPath } from '../path';
import { RetroButton, RADIUS } from '../ui';
import * as sfx from '../sound';

/**
 * "What's on" — an index of the entire set, generated by walking the registry.
 *
 * Nothing here is written down: add a module to the tree and it appears in the
 * Guide, correctly counted, with no edit to this file. That is the point of it —
 * it's the proof that the registry is the system rather than a lookup table the
 * screens happen to agree with.
 *
 * The page IS the screen, not a card floating on it — and the address trail
 * already names it, so it carries no title bar of its own.
 */

function countLeaves(node: OSNode, depth = 0): number {
  if (!isFolder(node)) return 1;
  if (depth > 3) return 0; // guard against a cyclic or pathological tree
  return node.children().reduce((n, c) => n + countLeaves(c, depth + 1), 0);
}

export default function GuideApp({ os }: AppProps) {
  const top = os.root.children();

  return (
    <div style={{
      position: 'absolute', inset: 0, paddingTop: 44, overflowY: 'auto',
      background: 'linear-gradient(180deg, #fdfbf5 0%, #f4efe2 100%)',
    }}>
        <div style={{ padding: '18px 22px 26px' }}>
          {top.map((node) => {
            const path = childPath('/', node.id);
            const children = isFolder(node) ? node.children() : [];
            return (
              <div key={node.id} style={{ marginBottom: 12 }}>
                <div style={{
                  display: 'flex', alignItems: 'center', gap: 8, marginBottom: 5,
                  paddingBottom: 4, borderBottom: '1px solid #d8d4cc',
                }}>
                  <span style={{ font: '700 14px/1 var(--font-sans)', color: '#1c1a17' }}>{node.name}</span>
                  <span style={{ font: '400 12px/1 var(--font-sans)', color: '#5a554d' }}>
                    {node.enabled === false
                      ? 'Coming soon'
                      : isFolder(node)
                        ? `${countLeaves(node)} items`
                        : 'Application'}
                  </span>
                  <span style={{ marginLeft: 'auto' }}>
                    <RetroButton label={`Open ${node.name}`} disabled={node.enabled === false} silent
                      onClick={() => { sfx.open(); os.navigate(path); }}
                      style={{ height: 22 }}>
                      OPEN
                    </RetroButton>
                  </span>
                </div>

                {children.length > 0 && (
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                    {children.map((c) => (
                      <button
                        key={c.id}
                        type="button"
                        disabled={c.enabled === false}
                        onPointerEnter={() => c.enabled !== false && sfx.hover()}
                        onClick={() => { sfx.open(); os.navigate(childPath(path, c.id)); }}
                        style={{
                          border: 'none', borderRadius: RADIUS, cursor: c.enabled === false ? 'default' : 'pointer',
                          padding: '4px 9px',
                          background: c.enabled === false ? '#efeee9' : '#eef2f9',
                          color: c.enabled === false ? '#9a958c' : '#2a4a8a',
                          font: '600 12px/1.3 var(--font-sans)',
                        }}
                      >
                        {c.name}
                        {isFolder(c) && c.enabled !== false && (
                          <span style={{ opacity: 0.65, fontWeight: 400 }}> · {countLeaves(c)}</span>
                        )}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>
    </div>
  );
}
