// Generated by scripts/source-f1-circuit-photos.ts. Do not edit by hand.
// Every entry is a verified Wikimedia Commons circuit image or map.

import type { F1WinImage } from '@/types/f1';

export const F1_CIRCUIT_PHOTOS: Record<string, F1WinImage> = {
  "Circuit de Spa-Francorchamps": {
    "file": "https://upload.wikimedia.org/wikipedia/commons/7/77/Circuit_de_Spa-Francorchamps%2C_April_22%2C_2018_SkySat_%28cropped%29.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/7/77/Circuit_de_Spa-Francorchamps%2C_April_22%2C_2018_SkySat_%28cropped%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=76971880",
    "title": "Circuit de Spa-Francorchamps, April 22, 2018 SkySat (cropped)",
    "label": "Circuit de Spa-Francorchamps",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Autodromo Nazionale di Monza": {
    "file": "File:Autodromo Nazionale Monza, April 22, 2018 SkySat.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Autodromo_Nazionale_Monza%2C_April_22%2C_2018_SkySat.jpg/250px-Autodromo_Nazionale_Monza%2C_April_22%2C_2018_SkySat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=77033590",
    "title": "Autodromo Nazionale Monza, April 22, 2018 SkySat.jpg",
    "label": "Autodromo Nazionale di Monza",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Circuit Mont-Tremblant": {
    "file": "File:Circuit Mont Tremblant.png",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Circuit%20Mont%20Tremblant.png",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circuit%20Mont%20Tremblant.png",
    "title": "Circuit Mont Tremblant track map",
    "label": "Circuit Mont-Tremblant",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Autódromo Hermanos Rodríguez": {
    "file": "File:Autódromo Hermanos Rodríguez, June 4, 2018 SkySat.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez%2C_June_4%2C_2018_SkySat.jpg/250px-Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez%2C_June_4%2C_2018_SkySat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=77063489",
    "title": "Autódromo Hermanos Rodríguez, June 4, 2018 SkySat.jpg",
    "label": "Autódromo Hermanos Rodríguez",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Kyalami": {
    "file": "File:Kyalami Circuit.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Kyalami_Circuit.png/330px-Kyalami_Circuit.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=89617942",
    "title": "Kyalami Circuit.png",
    "label": "Kyalami",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Scandinavian Raceway": {
    "file": "File:Scandinavian Raceway.svg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Scandinavian%20Raceway.svg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Scandinavian%20Raceway.svg",
    "title": "Track map of Scandinavian Raceway",
    "label": "Scandinavian Raceway",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Silverstone Circuit": {
    "file": "File:Race tracks at Silverstone - geograph.org.uk - 7189436.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Race_tracks_at_Silverstone_-_geograph.org.uk_-_7189436.jpg/330px-Race_tracks_at_Silverstone_-_geograph.org.uk_-_7189436.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=157678415",
    "title": "Race tracks at Silverstone - geograph.org.uk - 7189436.jpg",
    "label": "Silverstone Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Mosport International Raceway": {
    "file": "File:Mosport.svg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Mosport.svg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mosport.svg",
    "title": "Track map for Mosport International Raceway",
    "label": "Mosport International Raceway",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Autódromo Juan y Oscar Gálvez": {
    "file": "File:Circuito Nro 5 Autodromo Oscar y Juan Galvez.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Circuito_Nro_5_Autodromo_Oscar_y_Juan_Galvez.png/330px-Circuito_Nro_5_Autodromo_Oscar_y_Juan_Galvez.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=147235006",
    "title": "Circuito Nro 5 Autodromo Oscar y Juan Galvez.png",
    "label": "Autódromo Juan y Oscar Gálvez",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Autódromo José Carlos Pace": {
    "file": "File:Autódromo José Carlos Pace, July 3, 2018 SkySat.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace%2C_July_3%2C_2018_SkySat.jpg/250px-Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace%2C_July_3%2C_2018_SkySat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=77063487",
    "title": "Autódromo José Carlos Pace, July 3, 2018 SkySat.jpg",
    "label": "Autódromo José Carlos Pace",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Nivelles-Baulers": {
    "file": "File:Circuit Nivelles-Baulers.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Circuit_Nivelles-Baulers.png/250px-Circuit_Nivelles-Baulers.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=1115476",
    "title": "Circuit Nivelles-Baulers.png",
    "label": "Nivelles-Baulers",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Montjuïc": {
    "file": "File:Circuit_of_Montjuic_plate_Barcelona.JPG",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Circuit_of_Montjuic_plate_Barcelona.JPG",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circuit_of_Montjuic_plate_Barcelona.JPG",
    "title": "Circuit of Montjuic, Barcelona",
    "label": "Montjuïc",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Jarama": {
    "file": "File:Circuito de Madrid Jarama - RACE, o \"Circuito del Jarama\". Comunidad de Madrid. España, Spain.jpg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Circuito%20de%20Madrid%20Jarama%20-%20RACE%2C%20o%20%22Circuito%20del%20Jarama%22.%20Comunidad%20de%20Madrid.%20Espa%C3%B1a%2C%20Spain.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circuito%20de%20Madrid%20Jarama%20-%20RACE%2C%20o%20%22Circuito%20del%20Jarama%22.%20Comunidad%20de%20Madrid.%20Espa%C3%B1a%2C%20Spain.jpg",
    "title": "Aerial view of the Jarama Circuit",
    "label": "Jarama",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Circuit Paul Ricard": {
    "file": "https://upload.wikimedia.org/wikipedia/commons/5/59/Circuit_Paul_Ricard%2C_April_22%2C_2018_SkySat_%28cropped%29.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/5/59/Circuit_Paul_Ricard%2C_April_22%2C_2018_SkySat_%28cropped%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=76973234",
    "title": "Circuit Paul Ricard, April 22, 2018 SkySat (cropped)",
    "label": "Circuit Paul Ricard",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Nürburgring": {
    "file": "File:Nürburgring Luftaufnahme 2004.jpg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/N%C3%BCrburgring%20Luftaufnahme%202004.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:N%C3%BCrburgring%20Luftaufnahme%202004.jpg",
    "title": "Aerial photograph of the Nürburgring circuit",
    "label": "Nürburgring",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Circuit Park Zandvoort": {
    "file": "https://upload.wikimedia.org/wikipedia/commons/8/87/Motorsport_race_track_Circuit_Zandvoort_Formula_one_Grandprix_%2847856557161%29.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/8/87/Motorsport_race_track_Circuit_Zandvoort_Formula_one_Grandprix_%2847856557161%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=78972273",
    "title": "Motorsport race track Circuit Zandvoort Formula one Grandprix (47856557161)",
    "label": "Circuit Park Zandvoort",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Watkins Glen": {
    "file": "File:Sunrise at Watkins Glen Race Track (6030815113).jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Sunrise_at_Watkins_Glen_Race_Track_%286030815113%29.jpg/120px-Sunrise_at_Watkins_Glen_Race_Track_%286030815113%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=82516128",
    "title": "Sunrise at Watkins Glen Race Track (6030815113).jpg",
    "label": "Watkins Glen",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Fuji Speedway": {
    "file": "File:Race Track - 2019 6 hours of Fuji - FIA World Endurance Championship.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Race_Track_-_2019_6_hours_of_Fuji_-_FIA_World_Endurance_Championship.jpg/330px-Race_Track_-_2019_6_hours_of_Fuji_-_FIA_World_Endurance_Championship.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=84064178",
    "title": "Race Track - 2019 6 hours of Fuji - FIA World Endurance Championship.jpg",
    "label": "Fuji Speedway",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Long Beach": {
    "file": "File:Long beach street circuit.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Long_beach_street_circuit.png/330px-Long_beach_street_circuit.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49937634",
    "title": "Long beach street circuit.png",
    "label": "Long Beach",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Zolder": {
    "file": "File:Zolder racetrack aerial.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Zolder_racetrack_aerial.jpg/330px-Zolder_racetrack_aerial.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=137202336",
    "title": "Zolder racetrack aerial.jpg",
    "label": "Zolder",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Detroit Street Circuit": {
    "file": "File:Circuit Detroit F1 1983-1988.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Circuit_Detroit_F1_1983-1988.png/250px-Circuit_Detroit_F1_1983-1988.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=1116450",
    "title": "Circuit Detroit F1 1983-1988.png",
    "label": "Detroit Street Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Brands Hatch": {
    "file": "File:Brands Hatch (May 2011).jpg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Brands%20Hatch%20(May%202011).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brands%20Hatch%20(May%202011).jpg",
    "title": "Aerial view of Brands Hatch racing circuit",
    "label": "Brands Hatch",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Autódromo Internacional Nelson Piquet": {
    "file": "File:Jacarepaguá.svg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Jacarepagu%C3%A1.svg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jacarepagu%C3%A1.svg",
    "title": "Track map of Autódromo Internacional Nelson Piquet",
    "label": "Autódromo Internacional Nelson Piquet",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Autodromo Enzo e Dino Ferrari": {
    "file": "File:Imola_Circuit_-_Variante_Bassa_-_Summer_1973.jpg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Imola_Circuit_-_Variante_Bassa_-_Summer_1973.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Imola_Circuit_-_Variante_Bassa_-_Summer_1973.jpg",
    "title": "Imola Circuit, Variante Bassa, Summer 1973",
    "label": "Autodromo Enzo e Dino Ferrari",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Dijon-Prenois": {
    "file": "File:AC Cobra Tour Auto 2014 Circuit de Dijon Prenois 12.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/AC_Cobra_Tour_Auto_2014_Circuit_de_Dijon_Prenois_12.jpg/330px-AC_Cobra_Tour_Auto_2014_Circuit_de_Dijon_Prenois_12.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=32437912",
    "title": "AC Cobra Tour Auto 2014 Circuit de Dijon Prenois 12.jpg",
    "label": "Dijon-Prenois",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Circuit de Monaco": {
    "file": "File:Circuit de Monaco, April 1, 2018 SkySat.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Circuit_de_Monaco%2C_April_1%2C_2018_SkySat.jpg/250px-Circuit_de_Monaco%2C_April_1%2C_2018_SkySat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=76968862",
    "title": "Circuit de Monaco, April 1, 2018 SkySat.jpg",
    "label": "Circuit de Monaco",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Hockenheimring": {
    "file": "File:Aerial image of Hockenheimring (view from the southwest).jpg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20image%20of%20Hockenheimring%20(view%20from%20the%20southwest).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial%20image%20of%20Hockenheimring%20(view%20from%20the%20southwest).jpg",
    "title": "Aerial image of Hockenheimring",
    "label": "Hockenheimring",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Red Bull Ring": {
    "file": "File:Circuit A1 Ring (2).png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Circuit_A1_Ring_%282%29.png/250px-Circuit_A1_Ring_%282%29.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=69507471",
    "title": "Circuit A1 Ring (2).png",
    "label": "Red Bull Ring",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Autódromo do Estoril": {
    "file": "File:Circuito de Estoril 1972-1993.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Circuito_de_Estoril_1972-1993.png/250px-Circuito_de_Estoril_1972-1993.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=130414348",
    "title": "Circuito de Estoril 1972-1993.png",
    "label": "Autódromo do Estoril",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Adelaide Street Circuit": {
    "file": "File:Adelaide Street Circuit, February 2023 01.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Adelaide_Street_Circuit%2C_February_2023_01.jpg/250px-Adelaide_Street_Circuit%2C_February_2023_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=128302069",
    "title": "Adelaide Street Circuit, February 2023 01.jpg",
    "label": "Adelaide Street Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Circuit Gilles Villeneuve": {
    "file": "https://upload.wikimedia.org/wikipedia/commons/6/65/Circuit_Gilles-Villeneuve%2C_May_29%2C_2018_SkySat_%28cropped%29.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/6/65/Circuit_Gilles-Villeneuve%2C_May_29%2C_2018_SkySat_%28cropped%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=76969732",
    "title": "Circuit Gilles-Villeneuve, May 29, 2018 SkySat (cropped)",
    "label": "Circuit Gilles Villeneuve",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Hungaroring": {
    "file": "File:Hungary Formula One Circuit, Hungaroring (Ank Kumar) 01.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Hungary_Formula_One_Circuit%2C_Hungaroring_%28Ank_Kumar%29_01.jpg/330px-Hungary_Formula_One_Circuit%2C_Hungaroring_%28Ank_Kumar%29_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=100083211",
    "title": "Hungary Formula One Circuit, Hungaroring (Ank Kumar) 01.jpg",
    "label": "Hungaroring",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Circuito de Jerez": {
    "file": "File:Circuito Jerez 03.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Circuito_Jerez_03.jpg/250px-Circuito_Jerez_03.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=1637763",
    "title": "Circuito Jerez 03.jpg",
    "label": "Circuito de Jerez",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Suzuka Circuit": {
    "file": "File:Aéreo do Circuito de Suzuka e arredores - panoramio.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/A%C3%A9reo_do_Circuito_de_Suzuka_e_arredores_-_panoramio.jpg/500px-A%C3%A9reo_do_Circuito_de_Suzuka_e_arredores_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=56928215",
    "title": "Aéreo do Circuito de Suzuka e arredores - panoramio.jpg",
    "label": "Suzuka Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Phoenix street circuit": {
    "file": "File:Phoenix track.jpg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Phoenix%20track.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phoenix%20track.jpg",
    "title": "Phoenix street circuit track",
    "label": "Phoenix street circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Donington Park": {
    "file": "File:Donington Park, Race Track - geograph.org.uk - 5061557.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Donington_Park%2C_Race_Track_-_geograph.org.uk_-_5061557.jpg/330px-Donington_Park%2C_Race_Track_-_geograph.org.uk_-_5061557.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=133989162",
    "title": "Donington Park, Race Track - geograph.org.uk - 5061557.jpg",
    "label": "Donington Park",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Albert Park Grand Prix Circuit": {
    "file": "File:Albert Park & Australia Grand Prix Circuit.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Albert_Park_%26_Australia_Grand_Prix_Circuit.jpg/500px-Albert_Park_%26_Australia_Grand_Prix_Circuit.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=3275699",
    "title": "Albert Park & Australia Grand Prix Circuit.jpg",
    "label": "Albert Park Grand Prix Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Circuit de Barcelona-Catalunya": {
    "file": "File:Circuit de Barcelona-Catalunya, April 19, 2018 SkySat.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Circuit_de_Barcelona-Catalunya%2C_April_19%2C_2018_SkySat.jpg/250px-Circuit_de_Barcelona-Catalunya%2C_April_19%2C_2018_SkySat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=76968861",
    "title": "Circuit de Barcelona-Catalunya, April 19, 2018 SkySat.jpg",
    "label": "Circuit de Barcelona-Catalunya",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Circuit de Nevers Magny-Cours": {
    "file": "File:Circuit de Nevers Magny-Cours(01).png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Circuit_de_Nevers_Magny-Cours%2801%29.png/330px-Circuit_de_Nevers_Magny-Cours%2801%29.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=63547846",
    "title": "Circuit de Nevers Magny-Cours(01).png",
    "label": "Circuit de Nevers Magny-Cours",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Indianapolis Motor Speedway": {
    "file": "File:Indianapolis Motor Speedway Aerial August 2018.jpg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Indianapolis%20Motor%20Speedway%20Aerial%20August%202018.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Indianapolis%20Motor%20Speedway%20Aerial%20August%202018.jpg",
    "title": "Aerial view of Indianapolis Motor Speedway",
    "label": "Indianapolis Motor Speedway",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Sepang International Circuit": {
    "file": "File:Sepang International Circuit Grandstand Tower 2016 Malaysian GP.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Sepang_International_Circuit_Grandstand_Tower_2016_Malaysian_GP.jpg/330px-Sepang_International_Circuit_Grandstand_Tower_2016_Malaysian_GP.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=52086129",
    "title": "Sepang International Circuit Grandstand Tower 2016 Malaysian GP.jpg",
    "label": "Sepang International Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Istanbul Park": {
    "file": "File:Istanbul Park aerial.jpg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Istanbul%20Park%20aerial.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Istanbul%20Park%20aerial.jpg",
    "title": "Aerial photograph of Istanbul Park circuit",
    "label": "Istanbul Park",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Shanghai International Circuit": {
    "file": "File:Shanghai International Circuit, April 7, 2018 SkySat.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Shanghai_International_Circuit%2C_April_7%2C_2018_SkySat.jpg/250px-Shanghai_International_Circuit%2C_April_7%2C_2018_SkySat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=76964957",
    "title": "Shanghai International Circuit, April 7, 2018 SkySat.jpg",
    "label": "Shanghai International Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Marina Bay Street Circuit": {
    "file": "File:Singapore (SG), Marina Bay Street Circuit, F1 Pit Building -- 2019 -- 4478.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Singapore_%28SG%29%2C_Marina_Bay_Street_Circuit%2C_F1_Pit_Building_--_2019_--_4478.jpg/330px-Singapore_%28SG%29%2C_Marina_Bay_Street_Circuit%2C_F1_Pit_Building_--_2019_--_4478.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=85475016",
    "title": "Singapore (SG), Marina Bay Street Circuit, F1 Pit Building -- 2019 -- 4478.jpg",
    "label": "Marina Bay Street Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Yas Marina Circuit": {
    "file": "File:Yas Marina Circuit, October 12, 2018 SkySat (cropped).jpg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Yas%20Marina%20Circuit%2C%20October%2012%2C%202018%20SkySat%20(cropped).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yas%20Marina%20Circuit%2C%20October%2012%2C%202018%20SkySat%20(cropped).jpg",
    "title": "Aerial photograph of Yas Marina Circuit",
    "label": "Yas Marina Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Circuit of the Americas": {
    "file": "File:2002 US F1 Grand Prix - Circuit of the Americas, Austin, TX (54917351063).jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/2002_US_F1_Grand_Prix_-_Circuit_of_the_Americas%2C_Austin%2C_TX_%2854917351063%29.jpg/250px-2002_US_F1_Grand_Prix_-_Circuit_of_the_Americas%2C_Austin%2C_TX_%2854917351063%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=178424182",
    "title": "2002 US F1 Grand Prix - Circuit of the Americas, Austin, TX (54917351063).jpg",
    "label": "Circuit of the Americas",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Miami International Autodrome": {
    "file": "File:Circuito Internacional de Miami.jnp.jpg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Circuito%20Internacional%20de%20Miami.jnp.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circuito%20Internacional%20de%20Miami.jnp.jpg",
    "title": "Aerial photograph of Miami International Autodrome",
    "label": "Miami International Autodrome",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Baku City Circuit": {
    "file": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Baku_City_Circuit%2C_April_9%2C_2018_SkySat.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Baku_City_Circuit%2C_April_9%2C_2018_SkySat.jpg",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=76968863",
    "title": "Baku City Circuit, April 9, 2018 SkySat",
    "label": "Baku City Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Bahrain International Circuit": {
    "file": "File:Bahrain International Circuit back straight.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Bahrain_International_Circuit_back_straight.jpg/250px-Bahrain_International_Circuit_back_straight.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=9876883",
    "title": "Bahrain International Circuit back straight.jpg",
    "label": "Bahrain International Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Jeddah Corniche Circuit": {
    "file": "File:Jeddah.circuit.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Jeddah.circuit.jpg/500px-Jeddah.circuit.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=101735793",
    "title": "Jeddah.circuit.jpg",
    "label": "Jeddah Corniche Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Reims-Gueux": {
    "file": "File:2019-01-24 - Circuit de Reims-Gueux.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/2019-01-24_-_Circuit_de_Reims-Gueux.jpg/250px-2019-01-24_-_Circuit_de_Reims-Gueux.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=76093312",
    "title": "2019-01-24 - Circuit de Reims-Gueux.jpg",
    "label": "Reims-Gueux",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Circuit Bremgarten": {
    "file": "File:Circuit Bremgarten.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Circuit_Bremgarten.png/250px-Circuit_Bremgarten.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=1115427",
    "title": "Circuit Bremgarten.png",
    "label": "Circuit Bremgarten",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Aintree": {
    "file": "File:Circuit Aintree.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Circuit_Aintree.png/250px-Circuit_Aintree.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=1115417",
    "title": "Circuit Aintree.png",
    "label": "Aintree",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Sochi Autodrom": {
    "file": "File:Circuit Sochi-2015 T4.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Circuit_Sochi-2015_T4.jpg/250px-Circuit_Sochi-2015_T4.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=45471494",
    "title": "Circuit Sochi-2015 T4.jpg",
    "label": "Sochi Autodrom",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Autodromo Internazionale del Mugello": {
    "file": "File:AUTODROMO DEL MUGELLO- MUGELLO CIRCUIT- INGRESSO SCARPERIA SAN PIERO A SIEVE (FI).jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/AUTODROMO_DEL_MUGELLO-_MUGELLO_CIRCUIT-_INGRESSO_SCARPERIA_SAN_PIERO_A_SIEVE_%28FI%29.jpg/250px-AUTODROMO_DEL_MUGELLO-_MUGELLO_CIRCUIT-_INGRESSO_SCARPERIA_SAN_PIERO_A_SIEVE_%28FI%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=90915531",
    "title": "AUTODROMO DEL MUGELLO- MUGELLO CIRCUIT- INGRESSO SCARPERIA SAN PIERO A SIEVE (FI).jpg",
    "label": "Autodromo Internazionale del Mugello",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Autódromo Internacional do Algarve": {
    "file": "File:Algarve International Circuit (Unsplash).jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Algarve_International_Circuit_%28Unsplash%29.jpg/250px-Algarve_International_Circuit_%28Unsplash%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=62286991",
    "title": "Algarve International Circuit (Unsplash).jpg",
    "label": "Autódromo Internacional do Algarve",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Losail International Circuit": {
    "file": "File:Circuito Internacional de Losail.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Circuito_Internacional_de_Losail.png/250px-Circuito_Internacional_de_Losail.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=36921561",
    "title": "Circuito Internacional de Losail.png",
    "label": "Losail International Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Las Vegas Strip Street Circuit": {
    "file": "File:Las Vegas Strip Circuit.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Las_Vegas_Strip_Circuit.png/330px-Las_Vegas_Strip_Circuit.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=126658557",
    "title": "Las Vegas Strip Circuit.png",
    "label": "Las Vegas Strip Street Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Valencia Street Circuit": {
    "file": "https://upload.wikimedia.org/wikipedia/commons/8/84/Valencia_Street_Circuit_clue169.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/8/84/Valencia_Street_Circuit_clue169.jpg",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=39576038",
    "title": "File:Valencia Street Circuit clue169.jpg",
    "label": "Valencia Street Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Korean International Circuit": {
    "file": "File:Korea international circuit.svg",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Korea%20international%20circuit.svg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Korea%20international%20circuit.svg",
    "title": "Track map of Korean International Circuit",
    "label": "Korean International Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Buddh International Circuit": {
    "file": "File:Buddh International Circuit aerial.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Buddh_International_Circuit_aerial.jpg/330px-Buddh_International_Circuit_aerial.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=115724032",
    "title": "Buddh International Circuit aerial.jpg",
    "label": "Buddh International Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Las Vegas Street Circuit": {
    "file": "File:Las Vegas Strip Circuit.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Las_Vegas_Strip_Circuit.png/330px-Las_Vegas_Strip_Circuit.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=126658557",
    "title": "Las Vegas Strip Circuit.png",
    "label": "Las Vegas Street Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Fair Park": {
    "file": "File:Circuit Fair Park.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Circuit_Fair_Park.png/250px-Circuit_Fair_Park.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=1115438",
    "title": "Circuit Fair Park.png",
    "label": "Fair Park",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Riverside International Raceway": {
    "file": "File:Circuit Riverside.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Circuit_Riverside.png/250px-Circuit_Riverside.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=1115489",
    "title": "Circuit Riverside.png",
    "label": "Riverside International Raceway",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Prince George Circuit": {
    "file": "File:Prince George Circuit.png",
    "src": "https://commons.wikimedia.org/wiki/Special:FilePath/Prince%20George%20Circuit.png",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Prince%20George%20Circuit.png",
    "title": "Prince George Circuit track map",
    "label": "Prince George Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit photograph or circuit map; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Charade Circuit": {
    "file": "File:Circuit de Charade 2017-1.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Circuit_de_Charade_2017-1.jpg/330px-Circuit_de_Charade_2017-1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=101259072",
    "title": "Circuit de Charade 2017-1.jpg",
    "label": "Charade Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Rouen-Les-Essarts": {
    "file": "File:Circuit Rouen Les Essarts.png",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Circuit_Rouen_Les_Essarts.png/250px-Circuit_Rouen_Les_Essarts.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=1115490",
    "title": "Circuit Rouen Les Essarts.png",
    "label": "Rouen-Les-Essarts",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Le Mans": {
    "file": "File:Le Mans 24 Hour race track anno 2007 - panoramio.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Le_Mans_24_Hour_race_track_anno_2007_-_panoramio.jpg/250px-Le_Mans_24_Hour_race_track_anno_2007_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=40434024",
    "title": "Le Mans 24 Hour race track anno 2007 - panoramio.jpg",
    "label": "Le Mans",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  },
  "Okayama International Circuit": {
    "file": "File:Aeria; photograph of Okayama International Circuit.jpg",
    "src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Aeria%3B_photograph_of_Okayama_International_Circuit.jpg/250px-Aeria%3B_photograph_of_Okayama_International_Circuit.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=125286403",
    "title": "Aeria; photograph of Okayama International Circuit.jpg",
    "label": "Okayama International Circuit",
    "kind": "circuit",
    "reuseBasis": "Wikimedia Commons circuit image; source and attribution are recorded on the Commons page",
    "verificationStatus": "verified"
  }
};
